// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import "<Protobuf/GPBProtocolBuffers.h>"
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Log;
@class LogContent;
@class LogGroup;
@class LogTag;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MyRoot : GPBRootObject
@end

#pragma mark - LogContent

typedef GPB_ENUM(LogContent_FieldNumber) {
  LogContent_FieldNumber_Key = 1,
  LogContent_FieldNumber_Value = 2,
};

GPB_FINAL @interface LogContent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - Log

typedef GPB_ENUM(Log_FieldNumber) {
  Log_FieldNumber_Time = 1,
  Log_FieldNumber_ContentsArray = 2,
};

GPB_FINAL @interface Log : GPBMessage

/** UNIX Time Format */
@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LogContent*> *contentsArray;
/** The number of items in @c contentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contentsArray_Count;

@end

#pragma mark - LogTag

typedef GPB_ENUM(LogTag_FieldNumber) {
  LogTag_FieldNumber_Key = 1,
  LogTag_FieldNumber_Value = 2,
};

GPB_FINAL @interface LogTag : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - LogGroup

typedef GPB_ENUM(LogGroup_FieldNumber) {
  LogGroup_FieldNumber_LogsArray = 1,
  LogGroup_FieldNumber_Source = 2,
  LogGroup_FieldNumber_LogTagsArray = 3,
  LogGroup_FieldNumber_FileName = 4,
  LogGroup_FieldNumber_ContextFlow = 5,
};

GPB_FINAL @interface LogGroup : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Log*> *logsArray;
/** The number of items in @c logsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger logsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *source;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LogTag*> *logTagsArray;
/** The number of items in @c logTagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger logTagsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;

/** 该字段暂无效用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contextFlow;

@end

#pragma mark - LogGroupList

typedef GPB_ENUM(LogGroupList_FieldNumber) {
  LogGroupList_FieldNumber_LogGroupsArray = 1,
};

GPB_FINAL @interface LogGroupList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LogGroup*> *logGroupsArray;
/** The number of items in @c logGroupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger logGroupsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
